package(default_visibility = ["//lingvo/tasks/lm:__pkg__"])

licenses(["notice"])  # Apache 2.0

# First 100 training sentences from the 1 Billion Word Language Model Benchmark.
# http://www.statmt.org/lm-benchmark
filegroup(
    name = "lm1b_100",
    data = ["lm1b_100.txt"],
)
