package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "kitti_raw",
    data = glob([
        "kitti_raw_*",
    ]),
)

filegroup(
    name = "waymo_tutorial_frames",
    data = glob([
        "waymo_*",
    ]),
)

filegroup(
    name = "waymo_ap_testdata",
    data = glob([
        "waymo_decode_sparse_dev*",
    ]),
)
