# Milan-related tools

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

py_binary(
    name = "prepare_coco",
    srcs = ["prepare_coco.py"],
    deps = [
        # Implicit absl.app dependency.
        # Implicit absl.flags dependency.
        # Implicit absl.logging dependency.
        # Implicit apache_beam dependency.
        "//lingvo:compat",
        "//lingvo/core:base_layer",
        # Implicit numpy dependency.
        # Implicit tensorflow_datasets dependency.
        # Implicit tensorflow_hub dependency.
        # Implicit tensorflow_text dependency.
    ],
)
