package(default_visibility = ["//visibility:public"])

licenses(["notice"])

py_binary(
    name = "download_brown_corpus",
    srcs = ["download_brown_corpus.py"],
    deps = [
        "//lingvo:compat",
    ],
)
