package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache 2.0

py_binary(
    name = "download_brown_corpus",
    srcs = ["download_brown_corpus.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//lingvo:compat",
    ],
)
