package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache 2.0

py_binary(
    name = "download_lm1b",
    srcs = ["download_lm1b.py"],
    python_version = "PY2",
    deps = [
        # Implicit tensorflow dependency.
    ],
)
