package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "lenet_test_model",
    data = glob([
        "lenet_test_model*",
    ]),
)

filegroup(
    name = "en_1k_spm",
    data = glob([
        "en-1k.spm.*",
    ]),
)
